### ISSUE TITLE
Falha ao se conectar ao banco de dados

### ISSUE THREAD

**Issue by rodrigomolter** [Organizacao-Docunder/base-system#2]
# Falha ao se conectar ao banco de dados

Não é possível se conectar ao banco de dados através de ferramenta como pgAdmin, usando a porta 8080.

![image](https://github.com/Organizacao-Docunder/base-system/assets/57466763/5876c7c7-9eba-4caa-8979-d7a7840d1062)
Erro recebido
 

No entanto, **tive sucesso entrando com a porta 5432** (alterando no docker-compose), que é a porta default do PostgreSQL, e nesse cenário os dados persistiram de forma correta.

```
ports:
  - "5432:5432"
```

Minha sugestão é deixar a porta 5432 enquanto o erro é verificado, tendo em vista que é de baixa prioridade.

**Comment by rodrigomolter** [comment]
# Entendendo o porque do erro

A porta 5432 é a porta padrão usada pelo PostgreSQL para aceitar conexões de clientes e ele não esta mapeado para escutar novas conexões em portas diferentes.

# Solução
Há dois modos de se contornar isso

### 1. Mapear uma porta diferente apenas no host
```
ports:
    - "8080:5432"
```
O PostgreSQL dentro do contêiner está ouvindo na porta 5432, mas você está mapeando essa porta para a porta 8080 do host.

### 2. Alterar a porta padrão do PostgreSQL
Alterar as configurações do PostgreSQL para ouvir como padrão a porta 8080. <br>
Para isso, defina um comando dentro do `docker-compose.yaml` para alterar a porta do PostgreSQL para a desejada (8080)
```
command: postgres -c port=8080
```

# Melhor Opção
Atualmente, a melhor opção seria deixar a porta padrão como 5432 e mapear no host também como 5432
```
ports:
  - "5432:5432"
 ```

**Comment by devjoaobatista** [comment]
Oi Rodrigo, bom dia!

Issue corrigido, irei marcar  como fechado e se faltar algo pode  reabrir


att,

João
